name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node modules for back
        id: cache-back
        uses: actions/cache@v3
        with:
          path: "back/node_modules"
          key: cache-node-modules-${{ hashFiles('back/yarn.lock') }}
      - name: yarn install
        run: |
          cd back && yarn install
  ci-backend:
    runs-on: ubuntu-latest
    needs: prepare
    defaults:
      run:
        working-directory: ./back
    strategy:
      matrix:
        target: ["lint", "test", "build"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules for back
        id: cache-back
        uses: actions/cache@v3
        with:
          path: "back/node_modules"
          key: cache-node-modules-${{ hashFiles('back/yarn.lock') }}
      - run: yarn ${{ matrix.target }}
