name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["front", "back"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules for ${{ matrix.target }}
        id: "cache-${{ matrix.target }}"
        uses: actions/cache@v3
        with:
          path: "${{ matrix.target }}/node_modules"
          key: cache-node-modules-${{ hashFiles('${{ matrix.target }}/yarn.lock') }}
      - name: yarn install
        run: |
          cd ${{ matrix.target }} && yarn install
  ci-backend:
    runs-on: ubuntu-latest
    needs: prepare
    defaults:
      run:
        working-directory: ./back
    strategy:
      matrix:
        target: ["lint", "test", "build"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules for back
        id: cache-back
        uses: actions/cache@v3
        with:
          path: "back/node_modules"
          key: cache-node-modules-${{ hashFiles('back/yarn.lock') }}
      - run: yarn ${{ matrix.target }}
  ci-frontend:
    runs-on: ubuntu-latest
    needs: prepare
    defaults:
      run:
        working-directory: ./front
    strategy:
      matrix:
        target: ["lint", "build"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules for front
        id: cache-front
        uses: actions/cache@v3
        with:
          path: "front/node_modules"
          key: cache-node-modules-${{ hashFiles('front/yarn.lock') }}
      - run: yarn ${{ matrix.target }}
