name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: |
            ./front/node_modules
            ./back/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./front/yarn.lock') }}-${{ hashFiles('./back/yarn.lock') }}
      - name: yarn install front
        run: yarn install
        working-directory: ./front
      - name: yarn install back
        run: yarn install
        working-directory: ./back

  ci-backend:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        target: ["lint", "test", "build"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: |
            ./front/node_modules
            ./back/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./front/yarn.lock') }}-${{ hashFiles('./back/yarn.lock') }}
      - run: yarn ${{ matrix.target }}
        working-directory: ./back
  ci-frontend:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        target: ["lint", "build"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: |
            ./front/node_modules
            ./back/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./front/yarn.lock') }}-${{ hashFiles('./back/yarn.lock') }}
      - run: yarn ${{ matrix.target }}
        working-directory: ./front
